main/accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"

urlpatterns = [
    path('', views.homepage, name="homepage"),
    path("contact/", views.contact, name="contact"),
    path("register/", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name= "logout"),
    path("password_reset", views.password_reset_request, name="password_reset"),
]

main/cars/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.cars, name='cars'),
    path("info_car/<int:id>/", views.info_car, name="Car"),
    path("order_car/", views.order_car, name='order_car'),
    path("rent/", views.rent, name='rent'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('cars/', include('cars.urls')),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email_address = forms.EmailField(max_length=150)
    message = forms.CharField(widget=forms.Textarea, max_length=2000)


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

main/accounts/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib import messages
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes


def homepage(request):
    return render(request=request, template_name='accounts/home.html')


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "Website Inquiry"
        body = {
            'first_name': form.cleaned_data['first_name'],
            'last_name': form.cleaned_data['last_name'],
            'email': form.cleaned_data['email_address'],
            'message': form.cleaned_data['message'],
        }
        message = "\n".join(body.values())

        try:
            send_mail(subject, message, 'admin@example.com', ['admin@example.com'])
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        messages.success(request, "Message sent.")
        return redirect("accounts:homepage")
    form = ContactForm()
    return render(request, "accounts/contact.html", {'form': form})


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("accounts:homepage")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="accounts/register.html", context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("accounts:homepage")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="accounts/login.html", context={"login_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("accounts:homepage")


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "password/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="password/password_reset.html",
                  context={"password_reset_form": password_reset_form})

main/accounts/templates/accounts/contact.html
{% extends 'accounts/header.html' %}

  {% block content %}

		{% load crispy_forms_tags %}

		<div class="container p-5">
			<h1>Contact</h1>
			<h4>Contact us directly if you have any questions</h4>
			<p>
				Please write your name, email address and a message below if you have any questions.
				One of our staff members will be happy to contact you directly and answer your questions as soon as possible. 
			</p>
			<form method="post">
	        {% csrf_token %}
	            {{form|crispy}}
	            <button class="btn btn-primary" type="submit">Submit</button>
	        </form>
	    </div>

  {% endblock %}

main/accounts/templates/accounts/header.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    {% include 'includes/messages.html' %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="False" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarText">
            <div class="navbar-end">
              <a class="navbar-item" href="{% url 'accounts:homepage' %}">Homepage</a>
              <a class="navbar-item" href="{% url 'accounts:contact' %}">Contact</a>
              <a class="navbar-item" href="{% url 'cars' %}">Cars</a>
              {% if user.is_authenticated %}
              <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">Welcome, {{user.username}}</a>
                  <div class="navbar-dropdown">
                      <a class="navbar-item" href="/logout">Logout</a>
                  </div>
              </div>
              {% else %}
              <div class="navbar-item">
                  <a class="navbar-item button is-primary" href="{% url 'accounts:login' %}">Login</a>
              </div>
              {% endif %}
            </div>
         </div>
      </nav>

    {% block content %}

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

main/accounts/templates/accounts/home.html
{% extends 'accounts/header.html' %}

{% block content %}


    <div class="container mt-4">
        <div>
          <h1 class="display-4">Car Rent</h1>
          <p class="lead">Welcome on our site!!</p>
            <p class="lead">Please, <a href="/login">log in</a> or <a href="/register">create a new account,</a>
                then <a href="/cars">check out our cars</a> and rent them.
            </p>
          <hr class="my-4">
        </div>
    </div>

{% endblock %}

main/accounts/templates/accounts/login.html
{% extends "accounts/header.html" %}

{% block content %}      

{% load crispy_forms_tags %}

  <div class="container py-5">
    <h1>Login</h1>
    <form method="POST">
      {% csrf_token %}
      {{ login_form|crispy }}
      <button class="btn btn-primary" type="submit">Login</button>
    </form>
    <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
    <p class="text-center"><a href="/password_reset">Forgot password?</a></p>
  </div>

{% endblock %}

main/accounts/templates/accounts/register.html
{% extends "accounts/header.html" %}

{% block content %}

	{% load crispy_forms_tags %}

	<div class="container py-5">
		<h1>Register</h1>
		<form method="POST">
			{% csrf_token %}
			{{ register_form|crispy }}
			<button class="btn btn-primary" type="submit">Register</button>
		</form>
		<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
	</div>

{% endblock %}